data:
    !ft.ISLESDataModule {
        data_properties: ~/ISLES2022/dataset-dwi&adc.json,
        spacing: [2.0, 2.0, 2.0],
        spatial_size: [64, 64, 64],
        num_splits: 5,
        split: 4,
        batch_size: 2,
        num_workers: 4,
        cache_num: 4,
        cache_rate: 1.0,
        seed: 42,
    }

task:
    - !ft.SemanticSegmentation
    - network:
          - !monai.SwinUNETR
          - img_size: [64, 64, 64]
            spatial_dims: 3
            in_channels: 2
            out_channels: 1
            depths: [2, 2, 2, 2]
            feature_size: 48
            use_checkpoint: false
      inferer:
          !ft.ISLESInferer {
              spacing: [2.0, 2.0, 2.0],
              spatial_size: [64, 64, 64],
              overlap: 0.5,
              post: class,
          }
      loss:
          !monai.DiceCELoss {
              include_background: true,
              sigmoid: true,
              squared_pred: true,
          }
      metrics:
          dice:
              !ft.DiceMetric {
                  include_background: true,
                  include_zero_masks: true,
              }
          hd:
              !ft.HausdorffDistanceMetric {
                  include_background: true,
                  include_zero_masks: true,
                  percentile: 95,
              }
      optimizer:
          - !optim.AdamW
          - { lr: 0.0001, weight_decay: 0.01 }
      scheduler:
          - !ft.WarmupCosineSchedule
          - { warmup_steps: 2000, total_steps: 100000 }
      scheduler_config:
          interval: step

training:
    max_steps: 100000
    max_epochs: 9223372036854775807
    gpus: 2
    num_nodes: 1
    accelerator: ddp
    check_val_every_n_epoch: 10
    callbacks:
        - !pl.LearningRateMonitor { logging_interval: step }
        - !pl.ModelCheckpoint { every_n_train_steps: 50 }
        - !ft.SaveValResults {
              save_path: logs/isles2022-dwi&adc/fold4/swin-unetr/version_0/results.csv,
          }
    logger:
        !pl.TensorBoardLogger {
            save_dir: logs/isles2022-dwi&adc/fold4,
            name: swin-unetr,
        }

test:
    checkpoint:
        checkpoint_path: logs/isles2022-dwi&adc/fold4/swin-unetr/version_0/checkpoints/epoch=1999-step=99999.ckpt
    inferer:
        !ft.ISLESInferer {
            spacing: [2.0, 2.0, 2.0],
            spatial_size: [64, 64, 64],
            overlap: 0.5,
            post: class,
            write_dir: logs/isles2022-dwi&adc/fold4/swin-unetr/version_0/predictions,
        }
