data:
    !ft.BraTSDataModule {
        data_properties: ~/Decathlon/Task01_BrainTumour/dataset.json,
        spacing: [1.0, 1.0, 1.0],
        spatial_size: [128, 128, 128],
        num_splits: 5,
        split: 1,
        batch_size: 1,
        num_workers: 4,
        cache_num: 4,
        cache_rate: 1.0,
        seed: 42,
    }

task:
    - !ft.SemanticSegmentation
    - network:
          - !transbts.BTS
          - img_dim: 128
            patch_dim: 8
            num_channels: 4
            num_classes: 3
            embedding_dim: 512
            num_heads: 8
            num_layers: 4
            hidden_dim: 4096
            dropout_rate: 0.1
            attn_dropout_rate: 0.1
            conv_patch_representation: true
            positional_encoding_type: learned
      inferer:
          !ft.BraTSInferer {
              spacing: [1.0, 1.0, 1.0],
              spatial_size: [128, 128, 128],
              overlap: 0.5,
              post: one-hot-nested,
          }
      loss:
          !monai.DiceCELoss {
              include_background: true,
              sigmoid: true,
              squared_pred: true,
          }
      metrics:
          dice:
              !ft.DiceMetric {
                  include_background: true,
                  include_zero_masks: true,
              }
          hd:
              !ft.HausdorffDistanceMetric {
                  include_background: true,
                  include_zero_masks: true,
                  percentile: 95,
              }
      optimizer:
          - !optim.AdamW
          - { lr: 0.0001, weight_decay: 0.01 }
      scheduler:
          - !ft.WarmupCosineSchedule
          - { warmup_steps: 2000, total_steps: 100000 }
      scheduler_config:
          interval: step

training:
    resume_from_checkpoint: /data/leuven/336/vsc33647/scripts/factorizer/bin/logs/brats/fold1/transbts/version_0/checkpoints/epoch=310-step=60199.ckpt
    max_steps: 100000
    max_epochs: 9223372036854775807
    gpus: 2
    num_nodes: 1
    accelerator: ddp
    check_val_every_n_epoch: 50
    callbacks:
        - !pl.LearningRateMonitor { logging_interval: step }
        - !pl.ModelCheckpoint { every_n_train_steps: 50 }
        - !ft.SaveValResults {
              save_path: logs/brats/fold1/transbts/version_0/results.csv,
          }
    logger: !pl.TensorBoardLogger { save_dir: logs/brats/fold1, name: transbts }

test:
    checkpoint:
        checkpoint_path: logs/brats/fold1/transbts/version_0/checkpoints/epoch=515-step=99999.ckpt
    inferer:
        !ft.BraTSInferer {
            spacing: [1.0, 1.0, 1.0],
            spatial_size: [128, 128, 128],
            overlap: 0.5,
            post: class,
            write_dir: logs/brats/fold1/transbts/version_0/predictions,
        }
